services:
  - type: web
    name: uni-stay-dbuu-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
